server:
  port: 8080
  session:
    cookie:
      max-age: 120
spring:
  application:
    name: spring_session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_session?useUnicode=true&characterEncoding=UTF-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: kraytsman
    password: 1111
    dbcp:
      max-active: 20
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: Select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5

ldap:
  serverURL: ldap://ldap.softjourn.if.ua
  root: dc=ldap,dc=sjua
  usersBase: ou=People,ou=Users